# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
    push:
        branches:
            - main # production
            - dev # development
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    environment:
      name: ${{ github.ref_name }}    # main or development
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DEPLOY_FILE: ${{ secrets.FLY_DEPLOY_FILE }}
    steps:
      # 1 Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Set up fly.io CLI
      - name: Set up fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      # 3 Deploy to fly.io
      - name: Deploy to fly.io
        run: |
            flyctl deploy --remote-only --config "$env:DEPLOY_FILE"